### PR TITLE
Cygwin: console: disabled 24 bit color support

### PR DESCRIPTION
**Pull request by TaleTN**
Fixes GfW issue #2854 for me. However, this simply disables 24 bit support altogether, so it might make someone somewhere unhappy. On the bright side: This commit is pretty trivial, and so it can easily be reverted when someone comes up with a proper /better solution.

### CODE REVIEW

**Comment by dscho** [comment]
Hmm. As you pointed out elsewhere, this is prone to make users unhappy.

Can we find out _which_ of the `has_con_24bit_colors` conditional code triggers the problem?

Also, I wonder why the simple change from letting the MSYS2 runtime default to `TERM=xterm` instead of `TERM=xterm-256color` did not fix it, when doing the same manually _did_ fix it.

Further, I guess that there might be a problem with `usr/share/terminfo/78/xterm-256color` (and `usr/lib/terminfo/78/xterm-256color`, which is a copy). Maybe I could ask you to investigate that angle?

**Comment by TaleTN** [comment]
> Can we find out _which_ of the `has_con_24bit_colors` conditional code triggers the problem?

Maybe, but then I will first have to figure out how to build stuff locally, instead of misusing the GitHub workflow system as a remote build environment. Any pointers on how to setup a local build environment for msys2-runtime?

> Also, I wonder why the simple change from letting the MSYS2 runtime default to `TERM=xterm` instead of `TERM=xterm-256color` did not fix it, when doing the same manually _did_ fix it.

Like I said before, term=xterm did fix the home/end keys and restored the screen for me, but it still didn't display the final message properly.

Note that enabling the "Use legacy console" checkbox on the Options tab of the Windows 10 Command Prompt does fix the issue completely, but that's not something I'm prepared to do (because it's a non-default, system-wide setting, that e.g. also disables Ctrl-C/V copy/pasting).

> Further, I guess that there might be a problem with `usr/share/terminfo/78/xterm-256color` (and `usr/lib/terminfo/78/xterm-256color`, which is a copy). Maybe I could ask you to investigate that angle?

I guess I can install the current GfW, and then just edit those files, right? If so, then I should probably try that first, before attempting to build msys2-runtime locally.

**Comment by TaleTN** [comment]
Actually turns out those are binary files, so I can't really edit them. Still, I've been playing around with set term= in my .vimrc, and here is what I've found:

GfW 2.26.2: Only set term=cygwin works, both xterm and xterm-256color mess up the display (it looks like both clear and restore screen don't work). No set term= also works, probably because it uses term=cygwin by default.

GfW 2.32.0.2: Both set term=xterm and xterm-256color almost work (home/end keys work, display looks good), until you exit Vim, then it displays the final message without line-feeds. Both set term=cygwin and no set term= don't work (no home/end, messed up display). This seems to suggest that term=cygwin is still the default, but shouldn't xterm-256color be the default on a modernish Win10? It's almost as if set term=XXX doesn't really work, maybe because it only sets Vim in that mode, but not some other tools? I dunno.

I could still attempt to build msys2-runtime myself, and see if I can figure out which of the has_con_24bit_colors breaks things for me, if that would help.

**Comment by dscho** [comment]
> Any pointers on how to setup a local build environment for msys2-runtime?

Yes: https://github.com/git-for-windows/git/wiki/Building-msys2-runtime

> > Also, I wonder why the simple change from letting the MSYS2 runtime default to `TERM=xterm` instead of `TERM=xterm-256color` did not fix it, when doing the same manually _did_ fix it.
> 
> Like I said before, term=xterm did fix the home/end keys and restored the screen for me, but it still didn't display the final message properly.

Oh. I missed that there was a problem with the final message. Could you remind me what that problem was?

> Note that enabling the "Use legacy console" checkbox on the Options tab of the Windows 10 Command Prompt does fix the issue completely, but that's not something I'm prepared to do (because it's a non-default, system-wide setting, that e.g. also disables Ctrl-C/V copy/pasting).

Ah, that's where your idea came from to detect whether legacy mode is enabled, and special-casing things based on that flag.

If we could find out _what part_ of the `has_con_24bit_colors` conditional code behaves incorrectly unless legacy mode is enabled, I would be very much in favor of adding code that fixes this specifically, without painting that broad "disable `has_con_24bit_colors` altogether" brush.

> > Further, I guess that there might be a problem with `usr/share/terminfo/78/xterm-256color` (and `usr/lib/terminfo/78/xterm-256color`, which is a copy). Maybe I could ask you to investigate that angle?
> 
> I guess I can install the current GfW, and then just edit those files, right? If so, then I should probably try that first, before attempting to build msys2-runtime locally.

Those files are binary, and I think you need to use special tools to edit them.

*clicketyclick*

A quick web search produces this: https://linux.die.net/man/5/terminfo. Apparently, you need to use the `captoinfo`/`infotocap` tools to make sense of the binary files.

> I could still attempt to build msys2-runtime myself, and see if I can figure out which of the has_con_24bit_colors breaks things for me, if that would help.

I think that would be very useful. In particular the https://github.com/git-for-windows/git/wiki/Building-msys2-runtime#rebuild-the-msys2-runtime section should be helpful.

That Wiki page should probably be updated, by the way: These days, it should be as easy as following these steps to build an MSYS2 runtime:

1. download and install [the Git for Windows SDK](https://gitforwindows.org/#download-sdk)
2. `sdk build msys2-runtime`
3. `cd src/msys2-runtime/winsup/cygwin`
4. Look around for the changes you want to make
5. `sdk build msys2-runtime`
6. The `msys0.dll` that was generated can now be copied into an unpacked Portable Git, replacing `usr\bin\msys-2.0.dll`
7. In a CMD or PowerShell window, you can then `cd` to the unpacked Portable Git and start an interactive Bash session via `bin\bash.exe -li`
8. Whenever you need to re-build, you need to quit that interactive Bash session so that the `msys-2.0.dll` is not in use when you replace it with the newly-built `msys0.dll`.

I am struggling a bit to find time to do All The Things right now, what with the woes that prevented Git for Windows v2.33.0 from being released yesterday. Could I ask you, if you have a moment, to edit the Wiki page for me, after you verified that the steps I outlined above are correct?

**Comment by TaleTN** [comment]
> Oh. I missed that there was a problem with the final message. Could you remind me what that problem was?

The 2nd line in the final message would start at the horizontal position where the 1st line left off, the 3rd where the 2nd left off, etc. To me it seemed like it was missing '\r', and I now think this might be because it assumed these would be automatically inserted with '\n'.

> That Wiki page should probably be updated, by the way: These days, it should be as easy as following these steps to build an MSYS2 runtime:
> 
> 1. download and install [the Git for Windows SDK](https://gitforwindows.org/#download-sdk)
> 2. `sdk build msys2-runtime`
> 3. `cd src/msys2-runtime/winsup/cygwin`
> 4. Look around for the changes you want to make
> 5. `sdk build msys2-runtime`
> 6. The `msys0.dll` that was generated can now be copied into an unpacked Portable Git, replacing `usr\bin\msys-2.0.dll`
> 7. In a CMD or PowerShell window, you can then `cd` to the unpacked Portable Git and start an interactive Bash session via `bin\bash.exe -li`
> 8. Whenever you need to re-build, you need to quit that interactive Bash session so that the `msys-2.0.dll` is not in use when you replace it with the newly-built `msys0.dll`.

Great, thanks!

> I am struggling a bit to find time to do All The Things right now, what with the woes that prevented Git for Windows v2.33.0 from being released yesterday. Could I ask you, if you have a moment, to edit the Wiki page for me, after you verified that the steps I outlined above are correct?

Yeah sure, will do.

**Comment by TaleTN** [comment]
FYI: I've successfully my own msys-2.0.dll, so I've edited the Wiki a bit. Note that after the initial build I was left inside a 'makepkg' branch (I kinda exptected a 'main' branch). Also, there seems to be a new /newlib/libc/machine/i386/sys/fenv.h, I'm not sure what's up with that.

Anyway, I will report back if/when I've found anything.

**Comment by dscho** [comment]
> after the initial build I was left inside a 'makepkg' branch (I kinda exptected a 'main' branch).

See? That's why it is so useful if new contributors edit these wiki pages. I am way too familiar with the process and do not think anything of the `makepkg` branch anymore 😄 

> Also, there seems to be a new /newlib/libc/machine/i386/sys/fenv.h, I'm not sure what's up with that.

Right, this is a symlink that is checked out as a file by default (because of the way the MSYS2 runtime by default makes copies when asked to create symlinks).

But I thought that an `sdk build` fixes this? At least this is the intent of https://github.com/git-for-windows/MSYS2-packages/blob/d288f5d0e0b07609f7a59bbf872ca38f1b0d9dae/msys2-runtime/PKGBUILD#L184-L188

Ah, I see, when you do `sdk build msys2-runtime`, it implicitly prefixes `$PATH` with `/usr/bin/`, so you get the _MSYS_ version of `git.exe`, which still makes copies. To fix this, you could run `/cmd/git.exe reset --hard` and be done with it ;-)

Maybe we should do that as part of `msys2-runtime/PKGBUILD`? After the `git reset --hard`, test that `git status` comes back clean, if it doesn't, try to run `/cmd/git.exe reset --hard`, then verify `git status` again?

> Anyway, I will report back if/when I've found anything.

Excellent!

**Comment by dscho** [comment]
> @TaleTN any news?

@TaleTN gentle ping?

**Comment by TaleTN** [comment]
@dscho No news, except that the original issue was already fixed in v2.36.1, see issue #2854. So I guess I should close this pull request?

**Comment by dscho** [comment]
Yes, if there's no more work to be done, let's close it ;-)

**Pull request closed without merging**
