### PR TITLE
Rebase to 3.5.4

### PR DESCRIPTION
**Pull request by dscho**
This finally makes the jump to Cygwin v3.5, leaving Windows 7 and Windows 8 support behind.

It also cleans up _a lot_ of stuff, in particular dropping the upstreamed/backported patches. Basically, this is what is left in Git for Windows, on top of MSYS2:

```
*   27a56f38b5 Merge pull request #57 from rglidden/main
|\
| * b04c85093b msys2-runtime: restore fast path for current user primary group
|/
*   d348c78b68 Merge branch 'revert-pipe-blocking-regression'
|\
| * 0ee763fc22 Revert "Cygwin: pipe: Restore blocking mode for cygwin process at startup."
* |   0dc855f8d2 Merge pull request #37 from chirpnot/main
|\ \
| * | 81da75e85b Change the default base address for x86_64
| |/
* |   553fc9396c Merge branch 'wcstombs'
|\ \
| * | 060026beb8 Use MB_CUR_MAX == 6 by default
| * | f04a45615c Make paths' WCS->MBS conversion explicit
| |/
* |   ba3fefdab0 Merge pull request #10 from kblees/kb/symlinks
|\ \
| * | 7fcfaab3a9 Allow native symlinks to non-existing targets in 'nativestrict' mode
| |/
* |   61e5b3dda1 Merge pull request #1 from dscho/git-for-windows
|\ \
| |/
|/|
| * 2854bea098 Fixed path converting with non ascii char.
| * 7077e7e0f5 Mention the extremely useful small_printf() function
| * acf439b6dd Handle 8-bit characters under LOCALE=C
|/
* 52bdc892e9 Do not try to sync with Cygwin
* bfeec8172f dependabot: help keeping GitHub Actions versions up to date
* 386fe831b8 Bump actions/checkout from 2 to 4
* ce42b7f7fd fixup!!! CI: add a GHA for doing a basic build test
* a98eedda40 Merge branch 'msys2-3.5.4'
```

This addresses https://github.com/git-for-windows/git/issues/5110

### CODE REVIEW

**Comment by rimrul** [comment]
The commit ordering is a little weird.

`bfeec81` should probably come before `386fe83`.
`52bdc89` would also make sense before `386fe83` if we reorder things.

Nit: `386fe83` talks about updating `actions/checkout` from version `2`, but actually updates from version `3`.


We might want to backport https://inbox.sourceware.org/cygwin-patches/ZtWdJ7FtgZcAaA74@calimero.vinschen.de/T/#me1df4cacbe4a543f6e32e2732149d1684c4e05e3 to fix https://github.com/git-for-windows/git/issues/5115 and think about how that interacts with `0ee763f`.

**Comment by dscho** [comment]
> [bfeec81](https://github.com/git-for-windows/msys2-runtime/commit/bfeec8172ff08a99a94edaec7671676bf11c983f) should probably come before [386fe83](https://github.com/git-for-windows/msys2-runtime/commit/386fe831b8374e78e2b75306497d85c567bd7a4b).

And it should be upstreamed into `msys2/msys2-runtime` to begin with, I agree.

> [52bdc89](https://github.com/git-for-windows/msys2-runtime/commit/52bdc892e9037bc6e2ec8824888cff48a7e24db4) would also make sense before [386fe83](https://github.com/git-for-windows/msys2-runtime/commit/386fe831b8374e78e2b75306497d85c567bd7a4b) if we reorder things.

Or even better: the Actions-bumping should be upstreamed.

> Nit: [386fe83](https://github.com/git-for-windows/msys2-runtime/commit/386fe831b8374e78e2b75306497d85c567bd7a4b) talks about updating `actions/checkout` from version `2`, but actually updates from version `3`.

Yup, my fault, I failed to adjust it when rebasing and resolving merge conflicts.

> We might want to backport https://inbox.sourceware.org/cygwin-patches/ZtWdJ7FtgZcAaA74@calimero.vinschen.de/T/#me1df4cacbe4a543f6e32e2732149d1684c4e05e3 to fix [git-for-windows/git#5115](https://github.com/git-for-windows/git/issues/5115)

We probably even want to backport that fix to v3.4.x if it is a valid fix (or more: work-around, if you look at the patch you will see why I suspect that this does not fix the problem but only adds conditions under which things are papered over).

> and think about how that interacts with [0ee763f](https://github.com/git-for-windows/msys2-runtime/commit/0ee763fc226b8c7fb603d7d353a43de1981be06e).

That one is interesting: It is incorrect. I only noticed this, however, after quite a while. The problem was identified by t3701, which hung in Git's CI. When I added that revert, the CI passed again.

However, Git's code was incorrect. The actual fix for this problem is in https://github.com/gitgitgadget/git/pull/1648/commits/9d1613ba49b269b5ae14c74fd359c81237432c46, which [made it into Git v2.44.0](https://github.com/git/git/commit/1f9d2745fab473fda916642e535e7922cda421ca).

So now that this is fixed in Git, Git for Windows can drop that ugly MSYS2 runtime work-around, right?

Well, wrong. Git does not use a trunk-based development, but instead uses topic branches that apply patches on top of sometimes _very_ old commits. The CI runs associated with those topic branches would then fail.

I guess I should stop trying to care so much about Git's topic branches' CI failures because the described development process efficiently prevents CI fixes from mattering to topic branches, as those CI fixes will not be backported to individual topic branches, and therefore any effort to care about any CI failures other than the one of `master` and `next` would appear utterly futile.

**Comment by dscho** [comment]
> > We might want to backport https://inbox.sourceware.org/cygwin-patches/ZtWdJ7FtgZcAaA74@calimero.vinschen.de/T/#me1df4cacbe4a543f6e32e2732149d1684c4e05e3 to fix [git-for-windows/git#5115](https://github.com/git-for-windows/git/issues/5115)
> 
> We probably even want to backport that fix to v3.4.x

Here is the work-around PR: https://github.com/git-for-windows/msys2-runtime/pull/72

**Comment by dscho** [comment]
I've force-pushed an update after merging #72 (and after backporting the latest iteration of that patch that made it onto the `cygwin-3_5-branch`).

**Comment by dscho** [comment]
I just force-pushed an update, in preparation for integrating this in time for v2.47.0-rc0 (which is due tomorrow). Range-diff:

* 1:  d7d010e78b < -:  ---------- Revert "Cygwin: pipe: Restore blocking mode for cygwin process at startup."
* 2:  ffb402956e = 1:  f4fb564300 msys2-runtime: restore fast path for current user primary group
* -:  ---------- > 2:  900a410ab8 Cygwin: console: Disable cons_master_thread in win32-input-mode
* -:  ---------- > 3:  8854bb46db Cygwin: pipe: Fix a regression that raw_write() slows down
* 3:  80954399f3 = 4:  9d0d6e12ec Cygwin: pipe: Restore blocking mode of read pipe on close()/raw_read()

There are two new backports, fresh from the `cygwin-3_5-branch`, that I think I want to have in Git for Windows.

Also, this drops that Revert at long last that I had figured out to be an incorrect fix for the `add -i` hang: The correct fix was actually 19ed0dff8f3f19fc15e79d188d7bcaadf26f2f11 (which I came up with when trying to upstream Git for Windows' patches to msys2/msys2-runtime and was forced to have a much closer look than before). This fix has made it into v2.44.0 via v2.44.0-rc0~15, and I hope this is reasonably old enough by now that I can risk updating the minimal SDK (this has an impact on all of those topic branches at https://github.com/gitster/git which use an entire zoo of base commits that are too often well in the past: their CI builds will start to fail, and so will the CI builds of _new_ topic branches based on _old_ base commits).

**Comment by dscho** [comment]
I've verified in https://github.com/dscho/git-for-windows-automation/actions/runs/11039614276 that Git's test suite passes with this MSYS2 runtime version.

**Pull request merged**
