### PR TITLE
Support OneDrive better

### PR DESCRIPTION
**Pull request by dscho**
This backports patches that avoid hydrating files on OneDrive _just_ to `stat()` them.

See also https://github.com/msys2/msys2-runtime/issues/206.

### CODE REVIEW

**Review by rimrul — APPROVED** [review]

**Comment by dscho** [comment]
@rimrul thank you for approving! I plan on branch-deploying https://github.com/git-for-windows/msys2-runtime/pull/63 first, then https://github.com/git-for-windows/msys2-runtime/pull/68, and then this here PR. The branch-deployment requires a fast-forwarding history, so I'll rebase this PR branch once more before I can do that.

**Comment by rimrul** [comment]
> I plan on branch-deploying #63 first, then #68, and then this here PR

Do we need intermediate deployments if you intend to deploy a version containing all these patches shortly after?

**Comment by dscho** [comment]
> Do we need intermediate deployments if you intend to deploy a version containing all these patches shortly after?

Technically, we don't. Practically, I'd like to have them, also to exercise the new `msys2-runtime` support of the `/open pr` slash command.

**Pull request merged**
