### PR TITLE
Backport fix for hangup of less on quit after the window is resized.

### PR DESCRIPTION
**Pull request by rimrul**
This fixes https://github.com/git-for-windows/git/issues/4060
This fixes https://github.com/git-for-windows/git/issues/3438
This fixes https://github.com/git-for-windows/git/issues/3683

### CODE REVIEW

**Review by dscho — COMMENTED** [review]
Is this confirmed to fix the issue(s)?

**Comment by rimrul** [comment]
Not confirmed enough that I would just merge this. I wanted to ask people in the issues to test with the msys2 dll from the build artefact, but that has odd timestamps when I unzip it and I haven't investigated why yet.

**Comment by dscho** [comment]
> Not confirmed enough that I would just merge this. I wanted to ask people in the issues to test with the msys2 dll from the build artefact, but that has odd timestamps when I unzip it and I haven't investigated why yet.

@rimrul any news?

**Comment by qtow** [comment]
Using the `msys-2.0.dll` from the build artifact fixes the problem for me :+1:

**Comment by dscho** [comment]
@rimrul with this feedback, do you want to go forward to merge this PR?

**Comment by rimrul** [comment]
Sounds good to me.

**Comment by dscho** [comment]
I'm updating the patches and will open a PR in MSYS2-packages.

**Pull request merged**
