### PR TITLE
mkglobals: Fix EOL detection

### PR DESCRIPTION
**Pull request by orgads**
When the file has CRLF line endings, winsup.h is not removed, and
compilation fails for duplicate definitions.

### CODE REVIEW

**Comment by dscho** [comment]
I never encountered that problem... My guess is that `makepkg` checks out the source code with `core.autocrlf = false`, either explicitly, or by virtue of the MSys2 Git (`/usr/bin/git.exe`) defaulting to it.

Or did you edit the files with an editor that saves with CR/LF?

(Please note that I am not rejecting the patch; I just first want to understand better why it is needed.)

**Comment by orgads** [comment]
I do use makepkg, and yet have this problem. In MSYS2-packages/msys2-runtime core.autocrlf is indeed false (locally), but there is no global setting for it.

Notice that globals.h is a generated file, it isn't stored in git.

Moreover, the file seems to have only LF line-endings.

I'm still not completely sure what causes this. Maybe it is some conversion done by perl that *adds* CR?

**Comment by orgads** [comment]
Ok, I now found out that globals.cc which is the source for globals.h has CRLF line endings. This file is stored in git. Maybe the default value for core.autocrlf is true? I don't have a global setting in the git-sdk environment (no home directory at all)

**Comment by dscho** [comment]
Did you edit `globals.cc`, maybe? I ask because it has LF line endings here (and I do not recall doing anything special on my side apart from `makepkg -s`)...

**Comment by dscho** [comment]
Oh, I actually recall that I had that problem once: I ran `makepkg -s` in a *MINGW* shell, so the *MINGW* Git was doing the checking out. When I realized why it would not compile (wrong compiler...), I just removed the `src/` directory wholesale and let *MSys2* Git re-do the check out by running `makepkg -s` in an *MSys2* shell after that.

**Comment by dscho** [comment]
FWIW I just checked and it looks as if `mkglobals_h` has that problem even in Cygwin's source code (not that they run the danger of checking out anything with CR/LF, ever ;-)). Therefore we should consider sending this patch to the cygwin-patches mailing list, too, as described in the *When you have finalized your changes* section of https://cygwin.com/contrib.html... what do you think?

**Comment by orgads** [comment]
[Done](https://cygwin.com/ml/cygwin-patches/2015-q3/msg00016.html)

**Comment by dscho** [comment]
> Done

Perfect! Thanks!

**Comment by orgads** [comment]
[Applied upstream](https://cygwin.com/git/gitweb.cgi?p=newlib-cygwin.git;a=commit;h=ede983934cd75d8149e9fcd1b8419c1db6ada1fa).

**Comment by dscho** [comment]
This is truly awesome! Open Source for the win!

**Comment by orgads** [comment]
:D

**Pull request merged**
