### PR TITLE
Merge Cygwin 3.3 branch

### PR DESCRIPTION
**Pull request by orgads**
Contains important fixes for typeahead swapping and other console issues.

### CODE REVIEW

**Comment by orgads** [comment]
Build passed.

**Comment by dscho** [comment]
> Build passed.

Question is: does the build artifact fix the problem you reported?

**Comment by orgads** [comment]
> Question is: does the build artifact fix the problem you reported?

Yup ☺

**Comment by dscho** [comment]
Good.

There is a flurry of pty patches on the cygwin-patches list right now, so I would like to wait a little until it stabilizes, and then decide whether we have to take the patches early into Git for Windows, or whether we can wait for v3.3.4 to happen.

**Comment by orgads** [comment]
Sure, thanks.

**Comment by orgads** [comment]
@dscho I still experience mistypes keys, but I cannot reproduce it on Cygwin, only on msys2 (with the dll built here).

I (still) don't have a consistent reproduction, but if I get it correctly, it looks like one or more characters I type right when the prompt appears show up before the buffered characters.

For instance, I run git fetch, and while it is running I type `git status`, *sometimes* 1-2 characters "pop" to the left, so I get something like `tgit satus`.

Reported on [Cygwin mailing list](https://cygwin.com/pipermail/cygwin/2022-March/251049.html).

**Comment by dscho** [comment]
https://sourceware.org/pipermail/cygwin-patches/2022q1/011853.html seems to have a workaround?

**Comment by orgads** [comment]
> https://sourceware.org/pipermail/cygwin-patches/2022q1/011853.html seems to have a workaround?

Yes, I already included it [here](https://github.com/git-for-windows/msys2-runtime/pull/43/commits/9b8c60520b74718dae53618ca219aa587407541a)  for testing. I'll remerge.

**Comment by orgads** [comment]
Done.

**Comment by dscho** [comment]
> Done.

@orgads I take it the test was successful?

**Comment by orgads** [comment]
Yes.

**Comment by dscho** [comment]
Hmm. I just asked on IRC what the timeline is on Cygwin v3.3.5, and they said they're still chasing down a couple issues, and the gut feeling is that it will take days, maybe weeks to get v3.3.5 out the door.

I wonder whether we should bite the bullet and simply go ahead and merge the current `cygwin-3_3-branch` (we will most likely need the w32api fixes, i.e. the latest 2 patches, and maybe wait for a third one that'll be probably pushed soon, some `sleep()` one) and then package a new MSYS2 runtime for Git for Windows' use?

I think I like that idea, even if v3.3.5 will come out soon: This would give us the opportunity to test the MSYS2 runtime version for a few days before unleashing it to the masses.

@orgads what do you think?

**Comment by dscho** [comment]
FWIW I just created [the `msys-3_3-branch`](https://github.com/msys2/msys2-runtime/commits/msys2-3_3-branch). I think we need to do a full merging-rebase onto that because I noticed some merge conflicts:

```console
$ git show --remerge-diff orgads-1/merge-3.3
commit 78503c15ed8f0e0afdf85200770c4769b74f1539
Merge: 9f15ca2ed1 086895e81c
Author: Orgad Shaneh <orgads@gmail.com>
Date:   Sat Mar 19 20:04:09 2022 +0200

    Merge 'cygwin/cygwin-3_3-branch'
    
    Signed-off-by: Orgad Shaneh <orgads@gmail.com>

diff --git a/winsup/cygwin/exceptions.cc b/winsup/cygwin/exceptions.cc
remerge CONFLICT (content): Merge conflict in winsup/cygwin/exceptions.cc
index 0d6621271f..ed4b427b03 100644
--- a/winsup/cygwin/exceptions.cc
+++ b/winsup/cygwin/exceptions.cc
@@ -1581,7 +1581,6 @@ exit_sig:
 dosig:
   if (have_execed)
     {
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
       switch (si.si_signo)
         {
         case SIGUSR1:
@@ -1596,15 +1595,11 @@ dosig:
           goto done;
         default:
           sigproc_printf ("terminating captive process");
+          if (::cygheap->ctty)
+	    ::cygheap->ctty->cleanup_before_exit ();
           rc = exit_process_tree (ch_spawn, 128 + (sigExeced = si.si_signo));
           goto done;
         }
-=======
-      sigproc_printf ("terminating captive process");
-      if (::cygheap->ctty)
-	::cygheap->ctty->cleanup_before_exit ();
-      TerminateProcess (ch_spawn, sigExeced = si.si_signo);
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
     }
   /* Dispatch to the appropriate function. */
   sigproc_printf ("signal %d, signal handler %p", si.si_signo, handler);
diff --git a/winsup/cygwin/fhandler.h b/winsup/cygwin/fhandler.h
remerge CONFLICT (content): Merge conflict in winsup/cygwin/fhandler.h
index d898bd2e41..609326e915 100644
--- a/winsup/cygwin/fhandler.h
+++ b/winsup/cygwin/fhandler.h
@@ -1980,12 +1980,9 @@ class fhandler_termios: public fhandler_base
   }
   static bool path_iscygexec_a (LPCSTR n, LPSTR c);
   static bool path_iscygexec_w (LPCWSTR n, LPWSTR c);
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
-=======
   virtual void cleanup_before_exit () {}
   virtual bool need_console_handler () { return false; }
   virtual bool need_send_ctrl_c_event () { return true; }
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
 };
 
 enum ansi_intensity
diff --git a/winsup/cygwin/fhandler_console.cc b/winsup/cygwin/fhandler_console.cc
remerge CONFLICT (content): Merge conflict in winsup/cygwin/fhandler_console.cc
index 636743ff21..d2ed15a99b 100644
--- a/winsup/cygwin/fhandler_console.cc
+++ b/winsup/cygwin/fhandler_console.cc
@@ -320,37 +320,6 @@ fhandler_console::cons_master_thread (handle_set_t *p, tty *ttyp)
 	  wchar_t wc;
 	  char c;
 	  bool processed = false;
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
-	  termios &ti = ttyp->ti;
-	  pinfo pi (ttyp->getpgid ());
-	  if (pi && pi->ctty == ttyp->ntty
-	      && (pi->process_state & PID_NOTCYGWIN)
-	      && input_rec[i].EventType == KEY_EVENT && c == '\003')
-	    {
-	      bool not_a_sig = false;
-	      if (!CCEQ (ti.c_cc[VINTR], c)
-		  && !CCEQ (ti.c_cc[VQUIT], c)
-		  && !CCEQ (ti.c_cc[VSUSP], c))
-		not_a_sig = true;
-	      if (input_rec[i].Event.KeyEvent.bKeyDown)
-		{
-		  /* CTRL_C_EVENT does not work for the process started with
-		     CREATE_NEW_PROCESS_GROUP flag, so send CTRL_BREAK_EVENT
-		     instead. */
-		  if (pi->process_state & PID_NEW_PG)
-		    GenerateConsoleCtrlEvent (CTRL_BREAK_EVENT,
-					      pi->dwProcessId);
-		  else
-		    GenerateConsoleCtrlEvent (CTRL_C_EVENT, 0);
-		  if (not_a_sig)
-		    goto skip_writeback;
-		}
-	      processed = true;
-	      if (not_a_sig)
-		goto remove_record;
-	    }
-=======
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
 	  switch (input_rec[i].EventType)
 	    {
 	    case KEY_EVENT:
@@ -3820,18 +3789,12 @@ set_console_title (char *title)
 }
 
 static bool NO_COPY gdb_inferior_noncygwin = false;
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
-static void
-set_console_mode_to_native ()
-{
-=======
 
 void
 fhandler_console::set_console_mode_to_native ()
 {
   /* Setting-up console mode for non-cygwin app started by GDB. This is
      called from hooked CreateProcess() and ContinueDebugEvent(). */
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
   cygheap_fdenum cfd (false);
   while (cfd.next () >= 0)
     if (cfd->get_major () == DEV_CONS_MAJOR)
@@ -3839,18 +3802,10 @@ fhandler_console::set_console_mode_to_native ()
 	fhandler_console *cons = (fhandler_console *) (fhandler_base *) cfd;
 	if (cons->get_device () == cons->tc ()->getntty ())
 	  {
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
-	    termios *cons_ti = &((tty *) cons->tc ())->ti;
-	    fhandler_console::set_input_mode (tty::native, cons_ti,
-					      cons->get_handle_set ());
-	    fhandler_console::set_output_mode (tty::native, cons_ti,
-					       cons->get_handle_set ());
-=======
 	    termios *cons_ti = &cons->tc ()->ti;
 	    set_input_mode (tty::native, cons_ti, cons->get_handle_set ());
 	    set_output_mode (tty::native, cons_ti, cons->get_handle_set ());
 	    con.disable_master_thread = true;
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
 	    break;
 	  }
       }
@@ -3872,12 +3827,8 @@ CreateProcessA_Hooked
     mutex_timeout = 0; /* to avoid deadlock in GDB */
   gdb_inferior_noncygwin = !fhandler_termios::path_iscygexec_a (n, c);
   if (gdb_inferior_noncygwin)
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
-    set_console_mode_to_native ();
-=======
     fhandler_console::set_console_mode_to_native ();
   init_console_handler (false);
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
   return CreateProcessA_Orig (n, c, pa, ta, inh, f, e, d, si, pi);
 }
 
@@ -3891,12 +3842,8 @@ CreateProcessW_Hooked
     mutex_timeout = 0; /* to avoid deadlock in GDB */
   gdb_inferior_noncygwin = !fhandler_termios::path_iscygexec_w (n, c);
   if (gdb_inferior_noncygwin)
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
-    set_console_mode_to_native ();
-=======
     fhandler_console::set_console_mode_to_native ();
   init_console_handler (false);
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
   return CreateProcessW_Orig (n, c, pa, ta, inh, f, e, d, si, pi);
 }
 
@@ -3905,12 +3852,8 @@ ContinueDebugEvent_Hooked
      (DWORD p, DWORD t, DWORD s)
 {
   if (gdb_inferior_noncygwin)
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
-    set_console_mode_to_native ();
-=======
     fhandler_console::set_console_mode_to_native ();
   init_console_handler (false);
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
   return ContinueDebugEvent_Orig (p, t, s);
 }
 
diff --git a/winsup/cygwin/fhandler_termios.cc b/winsup/cygwin/fhandler_termios.cc
remerge CONFLICT (content): Merge conflict in winsup/cygwin/fhandler_termios.cc
index b857387f02..0d53ad25f5 100644
--- a/winsup/cygwin/fhandler_termios.cc
+++ b/winsup/cygwin/fhandler_termios.cc
@@ -149,12 +149,8 @@ tty_min::kill_pgrp (int sig, pid_t target_pgid)
       if (!p || !p->exists () || p->ctty != ntty || p->pgid != target_pgid)
 	continue;
       if (p->process_state & PID_NOTCYGWIN)
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
-	continue;
-=======
 	continue; /* Do not send signal to non-cygwin process to prevent
 		     cmd.exe from crash. */
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
       if (p == myself)
 	killself = sig != __SIGSETPGRP && !exit_state;
       else
@@ -555,53 +551,8 @@ fhandler_termios::line_edit (const char *rptr, size_t nread, termios& ti,
 
       if (ti.c_iflag & ISTRIP)
 	c &= 0x7f;
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
-      winpids pids ((DWORD) 0);
-      bool need_check_sigs = get_ttyp ()->pcon_input_state_eq (tty::to_cyg);
-      if (get_ttyp ()->pcon_input_state_eq (tty::to_nat))
-	{
-	  bool need_discard_input = false;
-	  for (unsigned i = 0; i < pids.npids; i++)
-	    {
-	      _pinfo *p = pids[i];
-	      if (c == '\003' && p && p->ctty == tc ()->ntty
-		  && p->pgid == tc ()->getpgid ()
-		  && (p->process_state & PID_NOTCYGWIN))
-		{
-		  /* CTRL_C_EVENT does not work for the process started with
-		     CREATE_NEW_PROCESS_GROUP flag, so send CTRL_BREAK_EVENT
-		     instead. */
-		  if (p->process_state & PID_NEW_PG)
-		    GenerateConsoleCtrlEvent (CTRL_BREAK_EVENT,
-					      p->dwProcessId);
-		  else
-		    GenerateConsoleCtrlEvent (CTRL_C_EVENT, 0);
-		  need_discard_input = true;
-		}
-	      if (p->ctty == get_ttyp ()->ntty
-		  && p->pgid == get_ttyp ()->getpgid () && !p->cygstarted)
-		need_check_sigs = true;
-	    }
-	  if (!CCEQ (ti.c_cc[VINTR], c)
-	      && !CCEQ (ti.c_cc[VQUIT], c)
-	      && !CCEQ (ti.c_cc[VSUSP], c))
-	    need_check_sigs = false;
-	  if (need_discard_input && !need_check_sigs)
-	    {
-	      if (!(ti.c_lflag & NOFLSH))
-		{
-		  eat_readahead (-1);
-		  discard_input ();
-		}
-	      ti.c_lflag &= ~FLUSHO;
-	      continue;
-	    }
-	}
-      if ((ti.c_lflag & ISIG) && need_check_sigs)
-=======
       bool disable_eof_key = false;
       switch (process_sigs (c, get_ttyp (), this))
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
 	{
 	case signalled:
 	  sawsig = true;
@@ -673,11 +624,7 @@ fhandler_termios::line_edit (const char *rptr, size_t nread, termios& ti,
 	    }
 	  continue;
 	}
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
-      else if (CCEQ (ti.c_cc[VEOF], c) && need_check_sigs)
-=======
       else if (CCEQ (ti.c_cc[VEOF], c) && !disable_eof_key)
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
 	{
 	  termios_printf ("EOF");
 	  accept_input ();
diff --git a/winsup/cygwin/spawn.cc b/winsup/cygwin/spawn.cc
remerge CONFLICT (content): Merge conflict in winsup/cygwin/spawn.cc
index c731e997b0..19de51e1f3 100644
--- a/winsup/cygwin/spawn.cc
+++ b/winsup/cygwin/spawn.cc
@@ -640,37 +640,11 @@ child_info_spawn::worker (const char *prog_arg, const char *const *argv,
 	  const int chk_order[] = {1, 0, 2};
 	  int fd = chk_order[i];
 	  fhandler_base *fh = ::cygheap->fdtab[fd];
-<<<<<<< 9f15ca2ed1 (Merge pull request #41 from dscho/virtual-dev-fd)
-	  if (fh && fh->get_major () == DEV_PTYS_MAJOR)
-	    {
-	      fhandler_pty_slave *ptys = (fhandler_pty_slave *) fh;
-	      if (ptys_primary == NULL)
-		ptys_primary = ptys;
-	    }
-	  else if (fh && fh->get_major () == DEV_CONS_MAJOR)
-	    {
-	      if (!iscygwin () && cons_native == NULL)
-		{
-		  fhandler_console *cons = (fhandler_console *) fh;
-		  cons_native = cons;
-		  cons_ti = &((tty *)cons->tc ())->ti;
-		  cons_owner = cons->get_owner ();
-		  tty::cons_mode conmode =
-		    (ctty_pgid && ctty_pgid == myself->pgid) ?
-		    tty::native : tty::restore;
-		  fhandler_console::set_input_mode (conmode,
-					   cons_ti, cons->get_handle_set ());
-		  fhandler_console::set_output_mode (conmode,
-					   cons_ti, cons->get_handle_set ());
-		}
-	    }
-=======
 	  if (fh && fh->get_major () == DEV_PTYS_MAJOR && ptys_primary == NULL)
 	    ptys_primary = (fhandler_pty_slave *) fh;
 	  else if (fh && fh->get_major () == DEV_CONS_MAJOR
 		   && !iscygwin () && cons_native == NULL)
 	    cons_native = (fhandler_console *) fh;
->>>>>>> 086895e81c (Cygwin: Fix "0x0x" in gmondump and ssp man pages)
 	}
 
       if (cons_native)
```

**Comment by orgads** [comment]
I'll remerge.

On my machine it works well, but on Win7 it crashes. Not sure why. I thought it will be solved by https://www.mail-archive.com/cygwin-patches@cygwin.com/msg09649.html but it isn't.

**Comment by dscho** [comment]
> On my machine it works well, but on Win7 it crashes.

@orgads there is nothing in the `cygwin-3_3-branch` that would fix this, other than what you already had merged...

**Comment by orgads** [comment]
I know. It crashes when running mintty with bash (the usual Git Bash prompt). Any idea how to debug it?

**Comment by dscho** [comment]
> I know. It crashes when running mintty with bash (the usual Git Bash prompt). Any idea how to debug it?

Other than using `gdb` from a PowerShell window? No... Maybe `strace`?

**Comment by dscho** [comment]
@orgads BTW this is the rebased version I was talking about: https://github.com/git-for-windows/msys2-runtime/compare/main...dscho:rebase-to-msys-3_3-branch

**Comment by dscho** [comment]
> > I know. It crashes when running mintty with bash (the usual Git Bash prompt). Any idea how to debug it?
> 
> Other than using `gdb` from a PowerShell window? No... Maybe `strace`?

Oh, and if you have a known-good version, you could try bisecting. What I ususally do with the MSYS2 runtime is to switch to a temporary branch, squash _all_ of the MSYS2 changes relative to Cygwin into one single patch, then run `git cherry-pick -n <patch> && make -j8 -C cygwin/winsup && cp cygwin/winsup/msys0.dll /path/to/temporary-msys2/usr/bin/msys-2.0.dll` for testing, and make sure that my `git bisect` only runs on the commits reachable from the _Cygwin_ branch.

**Comment by orgads** [comment]
Thank you. I'll try that.

The crash is not in mintty itself, I'm not sure what exactly crashes though.

**Comment by orgads** [comment]
Reported now: https://cygwin.com/pipermail/cygwin/2022-May/251370.html

**Comment by dscho** [comment]
> Reported now: https://cygwin.com/pipermail/cygwin/2022-May/251370.html

Good call.

BTW is this with `MSYS=enable_pcon`? If not, I suspect that @tyan0's patches forgot to accommodate for the `disable_pcon` mode and simply assumed that everybody has enabled them (which is not even possible on Windows 7)?

**Comment by orgads** [comment]
No `enable_pcon`.

**Comment by dscho** [comment]
> No `enable_pcon`.

Might make sense to specifically mention that to @tyan0, otherwise they might follow the wrong track in resolving this.

**Comment by dscho** [comment]
@orgads I would actually like to go forward with [the merging-rebase](https://github.com/git-for-windows/msys2-runtime/compare/main...dscho:rebase-to-msys-3_3-branch), but that Windows 7 issue puts a wrench into that. Should we simply revert (for now) the commit you found, or would that break things?

**Comment by orgads** [comment]
You can apply https://cygwin.com/pipermail/cygwin/2022-May/251382.html or just add `false &&` to the condition, until we have a proper fix.

I don't know what it may break.

**Comment by dscho** [comment]
So... according to https://cygwin.com/pipermail/cygwin/2022-May/251398.html, the breakage happens only when building the `bash` package in MSYS2's way, not when building it without any patches and from source.

@orgads maybe you can try rebuilding `bash` from [MSYS2's package definition](https://github.com/msys2/MSYS2-packages/tree/HEAD/bash) and see whether you can reproduce the problem?

**Comment by dscho** [comment]
> maybe you can try rebuilding `bash` from [MSYS2's package definition](https://github.com/msys2/MSYS2-packages/tree/HEAD/bash) and see whether you can reproduce the problem?

@orgads oh, and before you do that, maybe you can re-test with `bash.exe` as built [here](https://github.com/git-for-windows/MSYS2-packages/suites/6344887437/artifacts/228701778)?

**Comment by orgads** [comment]
> > maybe you can try rebuilding `bash` from [MSYS2's package definition](https://github.com/msys2/MSYS2-packages/tree/HEAD/bash) and see whether you can reproduce the problem?
> 
> @orgads oh, and before you do that, maybe you can re-test with `bash.exe` as built [here](https://github.com/git-for-windows/MSYS2-packages/suites/6344887437/artifacts/228701778)?

Still crashes with this build. I'll try to build locally.

**Comment by dscho** [comment]
@orgads just to make sure: the current `bash` _works_ on Windows 7 with the current MSYS2 runtime, and only after updating the MSYS2 runtime, it breaks?

**Comment by orgads** [comment]
Right.

**Comment by dscho** [comment]
@orgads the scenario @tyan0 [describes as being broken if we revert this commit](https://cygwin.com/pipermail/cygwin/2022-May/251412.html) strikes me as somewhat unconcerning because we handle Ctrl+C very differently in the MSYS2 runtime than the Cygwin runtime.

**Comment by dscho** [comment]
@orgads I prepared a new iteration of `rebase-to-msys-3_3-branch` and [the build](https://github.com/dscho/msys2-runtime/actions/runs/2283711759) is currently running. Could I ask you to test this on Windows 7, once finished?

**Comment by orgads** [comment]
> @orgads I prepared a new iteration of `rebase-to-msys-3_3-branch` and [the build](https://github.com/dscho/msys2-runtime/actions/runs/2283711759) is currently running. Could I ask you to test this on Windows 7, once finished?

Tested, it doesn't crash.

**Comment by dscho** [comment]
@orgads I pushed the merging-rebased version to `main` and [the build of the `msys2-runtime` package](https://dev.azure.com/Git-for-Windows/git/_build/results?buildId=99073&view=results) is running.

**Comment by orgads** [comment]
I'm closing this PR.

**Pull request closed without merging**
