### PR TITLE
fixup! Generate a .pdb file instead of a .dbg file

### PR DESCRIPTION
**Pull request by dakotahawkins**
Revert "Generate a .pdb file instead of a .dbg file"

This reverts commit 36aa0d34eef28b063ad70813f2b5fcb862ab6b18.

Signed-off-by: Dakota Hawkins <dakotahawkins@gmail.com>

Supersedes #19

Note: It takes two `rebase -i --autosquash ...` runs to completely remove the original commit. The first leaves an empty commit.

### CODE REVIEW

**Comment by dakotahawkins** [comment]
@dscho I was trying to ask how you wanted this done in [this comment](https://github.com/git-for-windows/msys2-runtime/pull/19#issuecomment-406370345), but to go ahead and get _something_ up I just guessed.

**Comment by dscho** [comment]
@dakotahawkins thanks for pulling through with this! And sorry for being so absent... I am trying to get a few things done on the [GitGitGadget](https://gitgitgadget.github.io) side of things...

**Comment by dakotahawkins** [comment]
@dscho No problem. The thing I couldn't figure out was whether you'd ever rewrite this repo's history to clean it up (since there are autosquash commits and I don't see other reversion patches, but know some patches that used to exist don't). What's your workflow for that here?

**Comment by dscho** [comment]
Right, the process is not really documented anywhere, I think.

I basically use the same strategy for the MSYS2 runtime as I use for the Git for Windows branch thicket: whenever a new version is released, I run a [merging rebase](https://github.com/git-for-windows/build-extra/blob/804f0241638a89e92d000f0282b206f815740049/shears.sh#L12-L18). This is the point in time when the `fixup!` and `squash!` commits are resolved.

Sadly, there is no `reword!` nor `drop!` yet, although I have a pretty good idea how these could be implemented.

BTW the way I release new Pacman packages is via `/usr/src/git-extra/please.sh upgrade <package>` (actually, this is run in a VSTS build that I trigger manually). The code to upgrade the `msys2-runtime` package is admittedly [involved](https://github.com/git-for-windows/build-extra/blob/804f0241638a89e92d000f0282b206f815740049/please.sh#L2791-L2890). Essentially, it runs the `update-patches.sh` script itself, so all you need to do is really open a PR at https://github.com/git-for-windows/msys2-runtime, and all I have to do after merging that PR is to trigger that job.

So next time, you need not bother with a PR at https://github.com/git-for-windows/MSYS2-packages ;-) (But I *do* appreciate your effort to make things as easy as possible on me!)

**Comment by dakotahawkins** [comment]
Well I figured https://github.com/git-for-windows/MSYS2-packages would require a PR this time since it had to revert parts of `PKGBUILD` (outside of the patches) that were changed manually.

But thanks for the rest of the explanation, that should help a lot in the future :)

**Comment by dscho** [comment]
Oh, you're right! :slaps-his-head:

**Pull request merged**
